### ISSUE TITLE
Support CentOS 7.7

### ISSUE THREAD

**Issue by nqb** [Orange-OpenSource/buildpkg-centos#1]
Hello,

Current CentOS 7 builds run on 7.6.

Is it possible to trigger new builds to support CentOS 7.7 ?

**Comment by lehcim** [comment]
The `buildpkg/centos:7` image is based on official `centos:7` image, which is currently version 7.6 :+1: 

```
$ docker run  centos:7 /bin/bash -c "yum -y -q install redhat-lsb-core && lsb_release -a"
[...]
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```
I see that Centos 7.7 was released a month ago, so the current centos:7 image is out of date ...
See https://github.com/CentOS/sig-cloud-instance-images/issues/150 for the availability of the 7.7 docker image.

If I remember correctly, docker-hub should automatically rebuild the `buildpkg/centos:7` image as soon as then `centos:7` one is released.

**Comment by nqb** [comment]
Thanks @lehcim for your feedback. I will update the issue when official Docker image will be released

**Comment by nqb** [comment]
> If I remember correctly, docker-hub should automatically rebuild the `buildpkg/centos:7` image as soon as then `centos:7` one is released.

@lehcim, it doesn't seems to be the case. 

CentOS 7.7 image is now available on DockerHub and `buildpkg/centos:7` has been rebuilt 4 days ago but image `buildpkg/centos:7` is still running CentOS 7.6 (same for `buildpkg/centos:latest`)

**Comment by lehcim** [comment]
Uh, okay, I thought it worked automatically ... I just launched manually a new build of the `buildpkg/centos:7` image.

**Comment by nbht** [comment]
I am unable to find centos 7.7 cloud image @https://cloud.centos.org/centos/7/images/
Kindly please confirm when it will be available

**Comment by nqb** [comment]
Hello @lehcim,

Just read that today: https://github.com/geerlingguy/docker-debian10-ansible/issues/11

It certainly explain why there is not autobuild ;-)
